services:
  mysql:
    container_name: sqlserver
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d